name: Godot CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: world-builder-3d

jobs:
  export-game:
    name: Export Game
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Import project
        run: |
          godot --headless --verbose --editor --quit
          
      - name: Build for Linux
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" build/linux/$EXPORT_NAME.x86_64
          
      - name: Upload Linux build
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux/
          
  test-project:
    name: Test Project
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Import and test
        run: |
          godot --headless --verbose --editor --quit
          echo "Project imported successfully"
          
      - name: Run GDScript tests
        run: |
          # Add test runner here when we have tests
          echo "Tests would run here"
